site_name: TreinaAí
site_description: Documentação oficial do projeto
site_author: Equipe TreinaAi
site_url: https://mdsreq-fga-unb.github.io/REQ-2025.2-T02-TreinaAi/
repo_url: https://github.com/mdsreq-fga-unb/2025.2-TO2-TreinaAi
repo_name: REQ-2025.2-T02-TreinaAi

theme:
  name: material
  language: pt-BR
  logo: assets/logoPNG.png
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      primary: red
      accent: orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Modo escuro
    - scheme: slate
      primary: orange
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Modo claro
  features:
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - repo.icon


nav:
  - Início: index.md
  - Visão do Produto e Projeto:
      - Cenario Atual do cliente e negócio: pages/VisaoDoProduto/CenarioAtual.md
      - Solução Proposta: pages/VisaoDoProduto/SolucaoProposta.md
      - Estratégias de Engenharia de Software: pages/VisaoDoProduto/estrategias.md
      - Cronogramas: pages/VisaoDoProduto/Cronograma.md
      - Interação entre Equipe e Cliente: pages/VisaoDoProduto/EquipeCliente.md
  - Requisitos de Software:
      - Engenharia de Requisitos: pages/Requisitos/ProcessoER.md
      - DoR e DoD: pages/Requisitos/DorDod.md
      - Funcionais: pages/Requisitos/RequisitosFunc.md
      - Não funcionais: pages/Requisitos/RequisitosNFunc.md
  - Backlog do Produto: pages/Backlog/geral.md
  - Entregas:
    - Unidade 1: pages/Entregas/Unidade01.md
    - Unidade 2: pages/Entregas/Unidade02.md
    - Unidade 3: pages/Entregas/Unidade03.md
  - Lições Aprendidas:
    - Unidade 1: pages/VisaoDoProduto/LicaoAprendida/Unidade1.md
    - Unidade 2: pages/VisaoDoProduto/LicaoAprendida/Unidade2.md
    - Unidade 3: pages/VisaoDoProduto/LicaoAprendida/Unidade3.md
  - Estudos de caso:
    - PBB: pages/EstudosCaso/pbb.md
    - USM: pages/EstudosCaso/usm.md
    - Diagrama UC: pages/EstudosCaso/DiagramaUC.md
  - Evidências:
    - Protótipos: pages/Evidencias/prototipos.md
    - Atas:
      - Ata 01: pages/Evidencias/atas/ata01.md
      - Ata 02: pages/Evidencias/atas/ata02.md
      - Ata 03: pages/Evidencias/atas/ata03.md
      - Ata 04: pages/Evidencias/atas/ata04.md
      - Ata 05: pages/Evidencias/atas/ata05.md
      - Ata 06: pages/Evidencias/atas/ata06.md
    - Aplicação da ER: pages/Evidencias/ER.md
    - Gravação de reunião: /pages/Evidencias/Reuniao01.md
    - App: docs/pages/Evidencias/App.md
  - Extras: 
    - Contribuição: pages/Extra/PoliticadeContribuicao.md


extra_css:
  - stylesheets/style.css

